working_dir:
    "/hps/nobackup/birney/users/ian/pilot"
lts_dir:
    "/nfs/research/birney/users/ian/pilot"
samples_file:
    "code/snakemake/20210701/config/samples.csv"
gcs_dir:
    "gs://medaka-video-store"
####################
# Containers
####################
gsutil:
    "docker://eu.gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:f335e76a8e0976cef547a8384f0b55582ad9a5a1f58fa5e6ac4d13cd3b2d81ea"
