input_dir:
    "/nfs/ftp/private/birney-res-ftp/upload/medaka/videos/ian_pilot/all"
sample_file:
    "pilot_paper/data/20201105_samples.csv"
split_script:
    "pilot_paper/code/scripts/20201111_split_videos.py"
fiji:
    "/nfs/software/birney/Fiji.app/ImageJ-linux64"
ilastik:
    "/nfs/software/birney/ilastik-1.3.3-Linux/run_ilastik.sh"
ilastik_train_proj:
    "ilastik/projects/20200316_pixclass.ilp"
ilastik_probs_out_dir:
    "probabilities/20200318/"
ilastik_track_proj:
    "ilastik/projects/20200317_antrack.ilp"
ilastik_tracks_out_dir:
    "csvs/20200318_fifth_pass/"
ilastik_objclass_proj:
    "ilastik/projects/20200313_objclass_backup.ilp"
ilastik_objclass_out_dir:
    "object_classification/20200318_fifth_pass/"
