__default__:
  memory: 5000
  n: 1
  name: "{rule}.{wildcards}"
  queue: "standard"
  outfile: "{log}"
# 02_tracking.smk
track_videos:
  memory: "{resources.mem_mb}"
coloured_trails:
  memory: "{resources.mem_mb}"