raw_data_dir:
    "/nfs/research/birney/projects/indigene/raw_data/ian_videos/ian_pilot/all"
working_dir:
    "/hps/nobackup/birney/users/ian/pilot"
lts_dir:
    "/nfs/research/birney/users/ian/pilot"
samples_file:
    "config/samples.csv"
samples_pairs_file:
    "config/samples_pairs.csv"
gcs_dir:
    "gs://medaka-video-store"
####################
# Containers
####################
opencv:
    /hps/nobackup/birney/users/ian/containers/pilot_paper/opencv_4.5.1.sif
gsutil:
    "docker://eu.gcr.io/google.com/cloudsdktool/cloud-sdk@sha256:f335e76a8e0976cef547a8384f0b55582ad9a5a1f58fa5e6ac4d13cd3b2d81ea"
