# HMM parameter optimisation

Using adapted code from `rule compare_params` in https://github.com/brettellebi/pilot_paper/blob/master/workflow/rules/05_param_optim.smk

Pipeline script: https://github.com/brettellebi/pilot_paper/blob/master/workflow/scripts/compare_params.R

```{r}
library(tidyverse)
library(plotly)
```

## Read in files

```{r}
CONC = list.files("/hps/nobackup/birney/users/ian/pilot/hmm_concordance_recode/",full.names = T, recursive = T)
KW = "/hps/nobackup/birney/users/ian/pilot/kruskal_wallis/out.rds"
```

## Process

```{r}
kw = readRDS(KW) %>% 
  dplyr::mutate(INTERVAL = as.numeric(INTERVAL)) %>% 
  dplyr::mutate(N_STATES = as.numeric(N_STATES))

conc = purrr::map_dfr(CONC, readRDS) %>% 
  dplyr::group_by(INTERVAL, N_STATES) %>% 
  # get mean across groups A and B
  dplyr::summarise(MEAN_CONC = mean(CONCORDANCE))

df = dplyr::left_join(kw, conc, by = c("INTERVAL", "N_STATES"))
```

## Plot

```{r}
pal = colorspace::sequential_hcl(length(unique(df$N_STATES)), palette = "ag_Sunset")

out_plot = df %>% 
  dplyr::mutate(N_STATES = factor(N_STATES, levels = sort(unique(N_STATES)))) %>% 
  dplyr::mutate(INTERVAL = factor(INTERVAL, levels = sort(unique(INTERVAL)))) %>% 
  ggplot(aes(MEAN_CONC, SUM_KW_STAT)) +
    geom_point(aes(size = INTERVAL, colour = N_STATES),
               alpha = 0.8) +
    ggrepel::geom_text_repel(aes(label = INTERVAL),
              size = 2,
              ) +
    theme_bw() +
    guides(size = guide_legend(title = "Interval\n(seconds)"),
           colour = guide_legend(title = "N states")) +
    scale_colour_manual(values = pal) +
    xlab("mean concordance between cross-validated HMM states") +
    ylab("summed Kruskal-Wallis statistic comparing frequency\nof time spent in each HMM state across medaka lines")

plotly::ggplotly(out_plot)
```
