# Model proportion of time spent in HMM states

```{r, message = F, warning = F}
library(tidyverse)
library(DT)
library()
```

## Read in and clean data

```{r}
IN = "/hps/nobackup/birney/users/ian/pilot/hmm_out/0.08/dist_angle/15.csv"
N_STATES = 15
```

```{r}
# Read 

raw = readr::read_csv(IN)

# Create line recode vector
line_vec = c("iCab", "HdrR", "HNI", "Kaga", "HO5")
names(line_vec) = c("icab", "hdr", "hni", "kaga", "ho5")

# Clean

df = raw %>% 
  # Get individual
  tidyr::unite(date, time, quadrant, fish,
               col = "indiv", 
               remove = F) %>% 
  # add `line` %>% 
  dplyr::mutate(line = dplyr::case_when(fish == "ref" ~ ref_fish,
                                        fish == "test" ~ test_fish)) %>% 
  # recode and order `assay` 
  dplyr::mutate(assay = stringr::str_replace(assay, pattern = "_", " "),
                assay = factor(assay, levels = c("open field", "novel object"))) %>% 
  # recode and order `line`
  dplyr::mutate(line = dplyr::recode(line, !!!line_vec),
                line = factor(line, levels = line_vec)) %>% 
  # convert `date` to factor
  dplyr::mutate(date = factor(date))

# Recode states by mean distance

rank_df = df %>% 
  dplyr::group_by(state) %>% 
  dplyr::summarise(mean_dist = mean(distance)) %>% 
  # rank
  dplyr::arrange(mean_dist) %>% 
  dplyr::mutate(rank = 1:nrow(.))

recode_vec = rank_df %>% 
  dplyr::pull(rank)
names(recode_vec) = rank_df %>% 
  dplyr::pull(state)

# Recode `state`

df = df %>% 
  dplyr::mutate(state_recode = dplyr::recode(state, !!!recode_vec),
                state_recode = factor(state_recode, levels = recode_vec))

```

## DGE

```{r}
# Get proportion of time each fish spent in each state
df_dge = df %>% 
  # remove iCab when paired with a different test fish
  dplyr::filter(!(fish == "ref" & test_fish != "icab")) %>% 
  ## count rows per fish per state
  dplyr::count(indiv, assay, line, date, time, quadrant, tank_side, state_recode) %>% 
  # add total row count per fish
  dplyr::add_count(indiv, assay, line, date, time, quadrant, tank_side, wt = n, name = "nn") %>% 
  # get proportion of time fish spent in each state
  dplyr::mutate(state_freq = n / nn)

# Split by assay

df_dge %>% 
  ggplot() + 
  geom_histogram(aes(state_freq, fill = state_recode),
                 bins = 40) +
  facet_grid(rows = vars(state_recode),
             cols = vars(assay)) +
  theme_bw() +
  scale_fill_viridis_d() +
  guides(fill = "none")
```


### Inverse-normalise

```{r}
# Add function
invnorm = function(x) {
  res = rank(x)
  res = qnorm(res/(length(res)+0.5))
  return(res)
}

df_dge = df_dge %>% 
  dplyr::group_by(assay, state_recode) %>% 
  dplyr::mutate(state_freq_invnorm = invnorm(state_freq)) %>% 
  dplyr::ungroup() %>% 
  dplyr::arrange(indiv, assay, line, date, time, quadrant, tank_side, state_recode)

df_dge %>% 
  ggplot() + 
  geom_histogram(aes(state_freq_invnorm, fill = state_recode),
                 bins = 40) +
  facet_grid(rows = vars(state_recode),
             cols = vars(assay)) +
  theme_bw() +
  scale_fill_viridis_d() +
  guides(fill = "none")
```

### Calculate variance explained

```{r}
aov_dge = df_dge %>% 
  dplyr::group_by(assay, state_recode) %>% 
  tidyr::nest() %>%
  dplyr::mutate(model = purrr::map(data, ~aov(
    state_freq_invnorm ~ date + time + quadrant + tank_side + line,
    data = .))) %>%
  select(-data) %>% 
  dplyr::mutate(model_tidy = purrr::map(model, broom::tidy)) %>%
  tidyr::unnest(model_tidy) %>% 
  rstatix::add_significance(p.col = "p.value")

DT::datatable(aov_dge %>% 
                dplyr::select(-model),
              options = list(pageLength = nrow(aov_dge)))
```

### Save to Google Drive

To `aov_state_freq` here: https://docs.google.com/spreadsheets/d/1_l72BZkmWyNAOfCUI8WGP4UfQuIPQtPZZmlRjQffvEs

```{r}
# Open field
aov_dge %>% 
  dplyr::filter(assay == "open field") %>% 
  # add variance explained
  dplyr::group_by(assay, state_recode) %>% 
  dplyr::mutate(tot_ss = sum(sumsq)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(var_expl_perc = (sumsq / tot_ss) * 100 ) %>%
  # select and rename key columns
  dplyr::select(State = state_recode,
                Variable = term,
                Statistic = statistic,
                `p-value` = p.value,
                Significance = p.value.signif,
                `Variance explained (%)` = var_expl_perc) %>% 
  # show only 2 decimals
  dplyr::mutate(dplyr::across(c("Statistic", 
                                #"p-value", 
                                "Variance explained (%)"),
                              ~ format(round(.x, 2), nsmall = 2))) %>% 
  googlesheets4::write_sheet(
    ss = "https://docs.google.com/spreadsheets/d/1_l72BZkmWyNAOfCUI8WGP4UfQuIPQtPZZmlRjQffvEs",
    sheet = "DGE_OF")

# Novel object
aov_dge %>% 
  dplyr::filter(assay == "novel object") %>% 
  # add variance explained
  dplyr::group_by(assay, state_recode) %>% 
  dplyr::mutate(tot_ss = sum(sumsq)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(var_expl_perc = (sumsq / tot_ss) * 100 ) %>%
  # select and rename key columns
  dplyr::select(State = state_recode,
                Variable = term,
                Statistic = statistic,
                `p-value` = p.value,
                Significance = p.value.signif,
                `Variance explained (%)` = var_expl_perc) %>% 
  # show only 2 decimals
  dplyr::mutate(dplyr::across(c("Statistic", 
                                #"p-value", 
                                "Variance explained (%)"),
                              ~ format(round(.x, 2), nsmall = 2))) %>% 
  googlesheets4::write_sheet(
    ss = "https://docs.google.com/spreadsheets/d/1_l72BZkmWyNAOfCUI8WGP4UfQuIPQtPZZmlRjQffvEs",
    sheet = "DGE_NO")
```

## SGE

```{r}
# Get proportion of time each fish spent in each state
df_sge = df %>% 
  # take all iCab fishes
  dplyr::filter(line == "iCab") %>% 
  ## count rows per fish per state
  dplyr::count(indiv, assay, test_fish, date, time, quadrant, tank_side, state_recode) %>% 
  # add total row count per fish
  dplyr::add_count(indiv, assay, test_fish, date, time, quadrant, tank_side, wt = n, name = "nn") %>% 
  # get proportion of time fish spent in each state
  dplyr::mutate(state_freq = n / nn)

# Split by assay

df_sge %>% 
  ggplot() + 
  geom_histogram(aes(state_freq, fill = state_recode),
                 bins = 40) +
  facet_grid(rows = vars(state_recode),
             cols = vars(assay)) +
  theme_bw() +
  scale_fill_viridis_d(option = "inferno") +
  guides(fill = "none")
```


### Inverse-normalise

```{r}
df_sge = df_sge %>% 
  dplyr::group_by(assay, state_recode) %>% 
  dplyr::mutate(state_freq_invnorm = invnorm(state_freq)) %>% 
  dplyr::ungroup() %>% 
  dplyr::arrange(indiv, assay, test_fish, date, time, quadrant, tank_side, state_recode)

df_sge %>% 
  ggplot() + 
  geom_histogram(aes(state_freq_invnorm, fill = state_recode),
                 bins = 40) +
  facet_grid(rows = vars(state_recode),
             cols = vars(assay)) +
  theme_bw() +
  scale_fill_viridis_d(option = "inferno") +
  guides(fill = "none")
```

### Calculate variance explained

```{r}
aov_sge = df_sge %>% 
  dplyr::group_by(assay, state_recode) %>% 
  tidyr::nest() %>%
  dplyr::mutate(model = purrr::map(data, ~aov(
    state_freq_invnorm ~ date + time + quadrant + tank_side + test_fish,
    data = .))) %>%
  select(-data) %>% 
  dplyr::mutate(model_tidy = purrr::map(model, broom::tidy)) %>%
  tidyr::unnest(model_tidy) %>% 
  rstatix::add_significance(p.col = "p.value")

DT::datatable(aov_sge %>% 
                dplyr::select(-model),
              options = list(pageLength = nrow(aov_sge)))
```

### Save to Google Drive

To `aov_state_freq` here: https://docs.google.com/spreadsheets/d/1_l72BZkmWyNAOfCUI8WGP4UfQuIPQtPZZmlRjQffvEs

```{r}
# Open field
aov_sge %>% 
  dplyr::filter(assay == "open field") %>% 
  dplyr::select(-model) %>% 
  # add variance explained
  dplyr::group_by(assay, state_recode) %>% 
  dplyr::mutate(tot_ss = sum(sumsq)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(var_expl_perc = (sumsq / tot_ss) * 100 ) %>%
  # select and rename key columns
  dplyr::select(State = state_recode,
                Variable = term,
                Statistic = statistic,
                `p-value` = p.value,
                Significance = p.value.signif,
                `Variance explained (%)` = var_expl_perc) %>% 
  # show only 2 decimals
  dplyr::mutate(dplyr::across(c("Statistic", 
                                #"p-value", 
                                "Variance explained (%)"),
                              ~ format(round(.x, 2), nsmall = 2))) %>% 
  googlesheets4::write_sheet(
    ss = "https://docs.google.com/spreadsheets/d/1_l72BZkmWyNAOfCUI8WGP4UfQuIPQtPZZmlRjQffvEs",
    sheet = "SGE_OF")

# Novel object
aov_sge %>% 
  dplyr::filter(assay == "novel object") %>% 
  dplyr::select(-model) %>% 
  # add variance explained
  dplyr::group_by(assay, state_recode) %>% 
  dplyr::mutate(tot_ss = sum(sumsq)) %>% 
  dplyr::ungroup() %>% 
  dplyr::mutate(var_expl_perc = (sumsq / tot_ss) * 100 ) %>%
  # select and rename key columns
  dplyr::select(State = state_recode,
                Variable = term,
                Statistic = statistic,
                `p-value` = p.value,
                Significance = p.value.signif,
                `Variance explained (%)` = var_expl_perc) %>% 
  # show only 2 decimals
  dplyr::mutate(dplyr::across(c("Statistic", 
                                #"p-value", 
                                "Variance explained (%)"),
                              ~ format(round(.x, 2), nsmall = 2))) %>% 
  googlesheets4::write_sheet(
    ss = "https://docs.google.com/spreadsheets/d/1_l72BZkmWyNAOfCUI8WGP4UfQuIPQtPZZmlRjQffvEs",
    sheet = "SGE_NO")
```